import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'German',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Chinese',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Gujarati',
    color: Colors.teal,
  ),
  Category(
    id: 'c11',
    title: 'Rajasthani',
    color: Colors.yellow,
  ),
  Category(
    id: 'c12',
    title: 'South Indian',
    color: Colors.orange,
  ),

];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spaghetti with Tomato Sauce',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    duration: 20,
    ingredients: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Toast Hawaii',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg',
    duration: 10,
    ingredients: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Classic Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wiener Schnitzel',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
    duration: 60,
    ingredients: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2'
          'c5',
      
    ],
    title: 'Salad with Smoked Salmon',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    duration: 15,
    ingredients: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      
    ],
    title: 'Delicious Orange Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pancakes',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Creamy Indian Chicken Curry',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    duration: 35,
    ingredients: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chocolate Souffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      
    ],
    title: 'Spring Rolls',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2018/03/15/12/16/food-3228057_960_720.jpg',
    duration: 35,
    ingredients: [
      '2 tsp oil',
'2 garlic cloves, finely chopped',
'1 inch ginger, finely chopped',
'1 carrot, thinly shredded',
'4 spring onions, finely chopped',
'1 cup cabbage, thinly shredded',
'1 tsp sugar',
'1-2 tsp chilli sauce',
'1 tsp soy sauce / soya sauce',
'2 tsp vinegar',
'1 tsp black pepper, crushed',
'salt to taste',
'1 tsp corn flour',
'7 spring roll pastry sheets / wrapper',
'1 tbsp maida / all-purpose flour / plain flour',
'oil for deep frying',
    ],
    steps: [
      'firstly, in a large kadai add oil along with finely chopped ginger and garlic.',
'also add finely chopped spring onions.',
'saute them for a minute or till the raw smell disappears.',
'furthermore, add shredded carrot and cabbage. saute them.',
'also add sugar, chilli sauce, soy sauce, vinegar, black pepper and salt.',
'mix everything well.',
'furthermore, add corn paste.',
'mix well and keep aside.',
'meanwhile, take spring roll pastry sheet and place spoonful of prepared stuffing.',
'pull and fold over the corner tightly till it reaches half the sheet.',
'furthermore, fold over sides like a envelope leaving no air pockets.',
'create crease and roll further.',
'at last, apply maida paste around the corners and seal the edges.',
'furthermore, deep fry the spring roll or bake them at 320 degrees F.',
'deep fry till they turn golden brown stirring occasionally.',
'once they turn golden brown, drain them over absorbent paper.',
'finally, serve crispy veg spring rolls hot with sweet chilli sauce or tomato sauce.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),

  Meal(
    id: 'm11',
    categories: [
      'c7',
      'c12',
    ],
    title: 'Masala Dosa',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/02/15/16/49/dosa-2069313_960_720.jpg',
    duration: 40,
    ingredients: [
      '2 tsp oil',
'2 tbsp chana dal',
'4 cloves garlic',
'1 inch ginger',
'1 onion, finely chopped',
'3 whole kashmiri red chilli, dried',
'¼ tsp turmeric / haldi',
'salt to taste',
'FOR ALOO BHAJI:',
'2 tsp oil',
'½ tsp mustard seeds',
'½ tsp jeera / cumin',
'pinch of hing / asafoetida',
'¾ tsp urad dal',
'¾ tsp chana dal',
'few curry leaves',
'½ onion, finely chopped',
'1 inch ginger, finely chopped',
'1 green chilli, finely chopped',
'½ tsp turmeric / haldi',
'salt to taste',
'2 potato, boiled & peeled',
'¼ cup water, adjust consistency',
'2 tbsp coriander leaves, finely chopped',
'1 tbsp lemon juice',
'2 cups dosa batter',
'4 tsp butter',
'½ cup cheese, cheddar or mozzarella',
    ],
    steps: [
      'firstly, heat the griddle and pour a ladleful of the dosa batter on it and spread it in a circular motion thin circle.',
'once the dosa dries out from top, add a dollop of butter.',
'also add prepared red chutney, adjust the chutney according to the spice level you are looking for.',
'and mix red chutney and butter together.',
'furthermore, mix and spread all over the dosa.',
'also spread 1 tbsp of prepared aloo bhaji over dosa.',
'additionally, grate cheese generously.',
'cook till the bottom of dosa turns golden brown.',
'then roll the dosa along with cheese - bhaji and cut half.',
'finally, cut half cheese dosa and serve immediately with chutney.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm12',
    categories: [
      'c5',
    ],
    title: 'Dumplings',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/09/08/22/17/soup-2730411_960_720.jpg',
    duration: 25,
    ingredients: [
      '1 cup semolina/bombay/sooji/rava, fine variety',
'½ onion, finely chopped',
'1 green chilli, finely chopped',
'1 tsp chana dal',
'1 tsp urad dal',
'1 tsp mustard seeds',
'1 tsp cumin seeds / jeera',
'pinch hing',
'½ inch ginger, finely chopped',
'3 cups water',
'1 sprig of curry leaves',
'1 tsp sugar, optional or add as required',
'2 tbsp oil or ghee',
'salt as required',
    ],
    steps: [
      'in a pan, heat 2 tbsp of oil and add 1 tsp mustard seeds, 1 tsp chana dal, 1 tsp cumin seeds and 1 tsp urad dal, hing and few curry leaves. fry till they begin to splutter.',
'now add the finely chopped onions, chilli, ginger and saute the onions till they become translucent or pinkish.',
'add 3 cups water to this mixture and add salt as required.',
'then add sugar. sugar is optional and you can skip it. we prefer a slight sweet taste in the pundi and hence we add it. stir well.',
'heat the water and let it come to a to a rolling boiling. now lower the flame to its lowest.'
'then add the rava slowly stirring immediately'
'you need to quickly stir and mix well else you can find lumps.'
'cover and allow the rava to steam for 1 minutes on the low flame. then swtich off the flame. now the rava is cooked. and ready to make balls.',
'wet your palm and take handful of dough and make oval shaped balls.'
'arrange these balls in a pan.'
'steam cook them for 15 minutes to 20 minutes.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
   Meal(
    id: 'm13',
    categories: [
      'c5',
    ],
    title: 'Hakka Noodles',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2019/07/18/23/21/hakka-noodles-4347560_960_720.jpg',
    duration: 20,
    ingredients: [
      '2 pack rice noodles',
'2 tsp oil',
'3 cloves garlic, finely chopped',
'1 inch ginger, finely chopped',
'½ onion, finely chopped',
'2 stem spring onion, chopped',
'½ carrot, thinly sliced',
'½ cup cabbage, thinly shredded',
'1 capsicum, thinly sliced',
'salt to taste',
'1 tbsp soy sauce',
'1 tbsp vinegar',
'1-2 tbsp chilli sauce',
'½ tsp pepper, crushed',
'¼ cup bean shoots,',
    ],
    steps: [
       'in boiling water add 2 packs of rice noodles or any noodles of your choice.',
'furthermore, stir once and get the water to boil. or cook as per instructions.',
'drain the water completely, and keep aside.',
'heat a large kadai with some oil.',
'further, saute garlic and ginger.',
'also saute onions and spring onions white on high flame.',
'furthermore, add chopped vegges like carrot, cabbage and capsicum.',
'saute till they shrink in size. do not over cook as the vegetables will loose the crunchiness.',
'also add salt, soy sauce, vinegar and chilli sauce. give a good mix.',
'further add the cooked noodles.',
'then add crushed pepper and bean shoots.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm14',
    categories: [
      'c11',
    ],
    title: 'Dal Bati',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://image.shutterstock.com/image-photo/rajasthani-traditional-cuisine-dal-baati-600w-780441559.jpg',
    duration: 90,
    ingredients: [
      '2 cup wheat flour / atta',
'¼ tsp salt',
'¼ tsp baking powder',
'¼ cup ghee / clarified butter',
'water to knead',
'½ cup moong dal / green gram dal',
    ],
    steps: [
      'firstly, in a large bowl take 2 cup wheat flour, ¼ tsp salt, ¼ tsp baking powder and ¼ cup ghee.',
'mix well making sure the dough is moist.',
'now add water as required and knead the dough.',
'pinch a small ball sized dough and roll with x impression.',
'place the rolled bati in each mould of appe pan',
'cover and cook on low flame for 30 minutes all sides.',
'dip the bati in ghee for more soft bati from inside.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm15',
    categories: [
      'c7',
      'c12',
    ],
    title: 'Idli',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/06/16/11/38/breakfast-2408818_960_720.jpg',
    duration: 20,
    ingredients: [
      '1 cup toor daal',
'2 tomatoes',
'½ onion',
'few curry leaves',
'1 inch ginger',
'few coriander leaves',
'2 green chillies',
'½ lemon',
    ],
    steps: [
      'firstly, wash and rinse the dal and put into a pressure cooker. in the same cooker add tomatoes and turmeric powder. pressure cook for 4 whistles.',
'once the pressure releases from the cooker, whisk the dal and tomatoes well.',
'meanwhile, chop onions, coriander leaves, ginger and chilli and keep them aside.',
'bullet idli sambar',
'furthermore, in a pan, add 1 tsp of oil. to the same pan add onions and fry them till golden brown.',
'now add curry leaves, ginger and chilli. fry for a minute.',
'add smashed daal to the kadai and bring to a boil.',
'additionally, season with salt and chilli powder.',
'bring it to boil. add water to maintain the consistency of sambar. boil it for 5 mins.',
'furthermore, garnish with coriander leaves and lemon juice, add a tsp of ghee and switch off.',
'prepare the tempering and add it over sambar.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm16',
    categories: [
      'c7',
      'c10',
    ],
    title: 'Dhokla',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://cdn.pixabay.com/photo/2017/01/10/18/00/indian-1969796_960_720.jpg',
    duration: 20,
    ingredients: [
      '1½ cup besan / gram flour',
'3 tbsp rava / semolina / suji, fine',
'½ tsp ginger paste',
'2 chilli, finely chopped',
'¼ tsp turmeric',
'1 tsp sugar',
'pinch hing / asafoetida',
'½ tsp salt',
'1 tbsp lemon juice',
'1 tbsp oil',
'1 cup water',
'½ tsp eno fruit salt',
    ],
    steps: [
      'firstly, in a large mixing bowl sieve 1½ cup besan and 3 tbsp rava.',
'add ½ tsp ginger paste, 2 chilli, ¼ tsp turmeric, 1 tsp sugar, pinch hing, ½ tsp salt, 1 tbsp lemon juice and 1 tbsp oil.',
'prepare a smooth batter adding 1 cup of water or as required.',
'additionally, add ½ tsp of eno fruit salt. you can alternatively use a pinch of baking soda.',
'immediately steam the dhokla batter for 20 minutes.',
'further, cut the dhokla and pour tempering.'
'garnish the dhokla with 2 tbsp chopped coriander leaves and 2 tbsp fresh grated coconut.',
'finally, serve instant khaman dhokla with green chutney and tamarind chutney.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];

